### ISSUE TITLE
id3 library discontinued

### ISSUE THREAD

**Issue by ildar** [LucJosin/on_audio_query#121]
plz switch to another, e.g. https://pub.dev/packages/id3tag
The root problem is with **id3 v 2.4 support** that the `id3` lib doesn't.

**Comment by LucJosin** [comment]
Hi @ildar, thanks for the suggestion. I didn't noticed that id3 package has been discontinued. 

I see that you are [having problem](https://github.com/moritz-weber/mucke/issues/82#issue-1706584919) with Cyrillic letters. Unfortunately, the usage of id3 package is specific to the web platform and [soon](https://github.com/users/LucJosin/projects/5) will be removed.

I'll close this issue. However, i will keep this conversation on [mucke](https://github.com/moritz-weber/mucke/issues/82) application to solve this problem.

**Comment by ildar** [comment]
Hello,
no, "Cyrillic" was the misleading part, sorry. The true problem is that
`id3` doesn't support id3 v2.4 (and that is explicitly written at id3's
page). Hence Mucke suffers from that lack.
CC: @moritz-weber
