### ISSUE TITLE
W/OnAudioQueryPlugin(32070): The application doesn't have access to the library

### ISSUE THREAD

**Issue by shijinthottiyil** [LucJosin/on_audio_query#130]
Can not fetch song from internal storage.Showing this error

**Comment by manthan-gohell7** [comment]
@shijinthottiyil Did you find any solution? I am also struggling with this issue

**Comment by shijinthottiyil** [comment]
yes bro check my git hub repo zap player in this older commits shijinthottiyil
(shijin thottiyil) (github.com) <https://github.com/shijinthottiyil>

**Comment by shijinthottiyil** [comment]
my issue was fixed by adding  @override
  void initState() {
    super.initState();
    requestPermission();
  }

  void requestPermission() async {
    if (!kIsWeb) {
      bool permissionStatus = await _audioQuery.permissionsStatus();
      if (!permissionStatus) {
        await _audioQuery.permissionsRequest();
      }
      setState(() {});
    }
    Permission.storage.request();
  }

  final _audioQuery = OnAudioQuery();

**Comment by LucJosin** [comment]
### The problem

This message will appear when no storage permission is requested.

https://github.com/LucJosin/on_audio_query/blob/90e9ab8d724fe8553920c3f14efa5459041d4989/packages/on_audio_query_android/android/src/main/kotlin/com/lucasjosino/on_audio_query/OnAudioQueryPlugin.kt#L134-L141

### Permissions

See how to add android [storage permission configuration](https://github.com/LucJosin/on_audio_query/blob/90e9ab8d724fe8553920c3f14efa5459041d4989/packages/on_audio_query_android/android/src/main/kotlin/com/lucasjosino/on_audio_query/OnAudioQueryPlugin.kt#L134-L141). 

Always check if the application has permission using the plugin method [permissionsStatus](https://pub.dev/documentation/on_audio_query/latest/on_audio_query/OnAudioQuery/permissionsStatus.html) and request using [permissionsRequest](https://pub.dev/documentation/on_audio_query/latest/on_audio_query/OnAudioQuery/permissionsRequest.html)

Alternatively, you can use another plugin like [permission_handler](https://pub.dev/packages/permission_handler)
