### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by junayedahamed** [LucJosin/on_audio_query#163]
provide solution please..............

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':on_audio_query_android'.
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgassistant/set-namespace for information about setting the namespace.

If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assis
to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-ue-assistant for general information about using the AGP Upgrade Assistant.

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
Get more help at https://help.gradle.org/.

**Comment by Kalph-ITT** [comment]
Even I am facing this same issue

**Comment by junayedahamed** [comment]
@Kalph-ITT I thought this package is not maintaining any more by it's maintainers

**Comment by Kalph-ITT** [comment]
@junayedahamed  have a look at this 
https://github.com/LucJosin/on_audio_query/pull/158/files
I did this and it worked

**Comment by junayedahamed** [comment]
@Kalph-ITT could you please describe briefly how could i use this ........ on pubspace.yml . Actually i didn't understand anything what changes made and why ......

**Comment by Kalph-ITT** [comment]
okay actually the issue is in the build gradle file in the project you can do one things go to source file of the package and in the folder  you can make the changes  done here https://github.com/LucJosin/on_audio_query/pull/158/files
[
<img width="962" alt="Screenshot 2024-12-25 at 6 40 05 PM" src="https://github.com/user-attachments/assets/a088a1be-2e54-404a-b7eb-bcbe1f31b854" />
<img width="962" alt="Screenshot 2024-12-25 at 6 39 46 PM" src="https://github.com/user-attachments/assets/28bd68a3-6be3-457f-8e5a-30078e48dde1" />
](url)

if you are still facing issues let me know @junayedahamed

**Comment by junayedahamed** [comment]
do i need  to fork the repo for making changes? @Kalph-ITT

**Comment by Kalph-ITT** [comment]
no you can change these settings in your local package as i have done it these changes in my local @junayedahamed

**Comment by junayedahamed** [comment]
![image](https://github.com/user-attachments/assets/1482c2a9-bc1e-4456-99c0-1f24288d82a6)

this is my build.graddle where shoul i change @Kalph-ITT

**Comment by Kalph-ITT** [comment]
no no you do not have to change your build gradle go to package build grade follow these steps 

1. Import the package in any file 
3. now hold ctrl/cmd click on the package you will be navigated to on_audio_query.dart
4. now click on folder name from top bread crumbs 
5. then select on_audio_query_android-1.1.0
6. select android and then select build.gradle 
7. there you need to make these changes i have done 
8. now save and rebuild the project 

let me know if you still need help @junayedahamed

**Comment by junayedahamed** [comment]
![image](https://github.com/user-attachments/assets/7772ff85-28a4-4ab2-8a33-cecad6907475)
@ @Kalph-ITT  it showing this now

**Comment by Kalph-ITT** [comment]
you have to add these lines also  in android @junayedahamed 

`
  namespace 'com.lucasjosino.on_audio_query'

 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
    `

**Comment by junayedahamed** [comment]
@Kalph-ITT thanks it's working now....

i get an error when i try to play music  did you faced this kind of problem ?

error:

I/flutter (11036): MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)

**Comment by Kalph-ITT** [comment]
No i have not faced this issue as i am not using this library for playing music .  I am using just to get the uri of file

**Comment by junayedahamed** [comment]
ok ... thank you
