### ISSUE TITLE
song name appears in all Songs List even after deleting it

### ISSUE THREAD

**Issue by Su-desh** [LucJosin/on_audio_query#67]
hi @LucJosin  i am getting a very weird error with this plugin .

I deleted a song with the following code 

```Dart

onTap: () async {
                File file = File(widget.singleTrack!.data);
                try {
                  file.deleteSync();
                  if (await file.exists()) {
                    print('Song not deleted');
                  } else {
                    audioDataClass.getMp3Data();
                    audioDataClass.update();
                  }
                } catch (e) {
                  print('$e');
                }

                Get.back();
              }
```

Song is deleted without any issue from the file system .

 But the problem is that this plugin still holds a reference to that song , because when we i use querySongs(); or queryAlbums();
it is showing the deleted song details in ListView, similar to other songs . this should not happen because that song is removed from storage .

I thought this might be a issue because i did not update the song list View after deleting that song but I tried Restarting the app , Flutter clean . 
But same result is shown , song is there in the querySongs list .

Android 11  (API 30) .

**Comment by huangcs427** [comment]
hi, I am using the latest version 2.6.0, and it still seems to have this problem. I need to use the following code during the loop to determine that I am using Android（HUAWEI P50 pro）.
```
tempList = [];
List<SongModel> querySongs = await _audioQuery.querySongs();
for (var i = 0; i < querySongs.length; i++) {
    var val = querySongs[i];
    File musicFile = File(val.data);
    if (!musicFile.existsSync()) continue;
    tempList.add(val);
}
```

**Comment by LucJosin** [comment]
Hi @huangcs427. If you're trying to delete the media, call the `scanMedia` after the `delete` method. At the moment this is the only way to notify the android MediaStore that some music has been removed.

You can see the example [here](https://github.com/LucJosin/on_audio_query#scanmedia)

**Comment by huangcs427** [comment]
> Hi @huangcs427. If you're trying to delete the media, call the `scanMedia` after the `delete` method. At the moment this is the only way to notify the android MediaStore that some music has been removed.
> 
> You can see the example [here](https://github.com/LucJosin/on_audio_query#scanmedia)

Thank you, Great. I'm sorry I didn't see this description.
