### ISSUE TITLE
How I can get Artwork in full resolution?

### ISSUE THREAD

**Issue by CesarArellano** [LucJosin/on_audio_query#69]
I try to put the artworkQuality prop with FilterQuality.high, but this not working for me 

Is there any other way to get Artwork in high quality?

Thx

**Comment by LucJosin** [comment]
In both `queryArtwork` and `QueryArtworkWidget` the parameters: `format`, `size` and `quality` will define the image quality. By default the plugin set to: `JPEG`, `200` and `100`.

Try changing from `JPEG`(Low image quality) to `PNG`(High image quality) and increasing the `size`. The **max** value to the parameter `quality` is **100**. Any value above will be replaced with **100**.

**Comment by CesarArellano** [comment]
Thx so much, I really appreciate your dedication for this package, approximately when you release version 3?
