### ISSUE TITLE
MediaDirType.ASSETS not working @3.0.0-beta.0

### ISSUE THREAD

**Issue by takapiroid88** [LucJosin/on_audio_query#82]
### directory
```
project_folder
- assets
    - audio
        - flutter_sample.mp3
```

### pubspec.yaml
```
flutter:
  assets:
    - assets/
    - assets/audio/  
```

### code
```
  final _query = OnAudioQuery();
  _query
      .querySongs(filter: MediaFilter.init(dirType: MediaDirType.ASSETS))
      .then(
    (value) {
      var titles = value.map((v) => v.title).toList();
      print("MediaDir Assets songs: $titles");
    },
  );
```

expected: output title -> flutter_sample.mp3 
result: output none

how to get my flutter assets mp3.

OS: Android11

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale ja-JP)                                                                                                                                                      Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by LucJosin** [comment]
Status of 3.0.0-beta.0 - #119
