### ISSUE TITLE
Last update 2.6.2 not feching songs in Android

### ISSUE THREAD

**Issue by Alvaro1dev** [LucJosin/on_audio_query#96]
Hi
I updated the plugin to version 2.6.2 in my app and the following instruction stop fetching the songs in Android:

final songs = await audioQuery.querySongs(path: folderPath);

I rolled back to version 2.6.1 and it works again.

**Comment by LucJosin** [comment]
Hi @Alvaro1dev, could you provide more details?

* Android version

**Comment by LucJosin** [comment]
I've tested using this configuration:
* Pixel 6 Pro
* Android 13 / API 33
* Emulator

### Code:

Using the [on_audio_query/example](https://github.com/LucJosin/on_audio_query/tree/main/on_audio_query/example) and adding **path** to **querySongs**

```dart
// code...
future: _audioQuery.querySongs(
  sortType: null,
  orderType: OrderType.ASC_OR_SMALLER,
  uriType: UriType.EXTERNAL,
  ignoreCase: true,
  path: "..",
),
```

### Output:

* Using internal folder: `/storage/emulated/0/Music`

```console
D/[OnAudiosQuery]: Selection: _data like '%/storage/emulated/0/Music/%'
D/[DispatchedCoroutine]:  Cursor: >>>>> Dumping cursor android.content.ContentResolver$CursorWrapperInner
    0 {
       _data=/storage/emulated/0/Music/audio.mp3
       _display_name=audio.mp3
       ...
    }
```

* Using sdcard folder: `/storage/XXXX-XXXX/Music/`

```console
D/[OnAudiosQuery]: Selection: _data like '%/storage/XXXX-XXXX/Music/%'
D/[DispatchedCoroutine]:  Cursor: >>>>> Dumping cursor android.content.ContentResolver$CursorWrapperInner
    0 {
       _data=/storage/XXXX-XXXX/Music/audio2.mp3
       _display_name=audio2.mp3
       ...
    }
```

> final songs = await audioQuery.querySongs(path: folderPath);

Could you provide an example of `folderPath`?

cc: @chaliseminas, @Alvaro1dev

**Comment by Alvaro1dev** [comment]
In my case, the flutter version cause the problem. It works well using flutter 3.3.10 and on_audio_query 2.6.1

Using flutter 3.7.7, on_audio_query 2.6.2 doesn't work. Version 2.6.1 works on Android 12 but not on Android 13.

Using flutter 3.3.10 on_audio_query 2.6.2 works only on Android 13.

FolderPath: "/storage/emulated/0/Music"

**Comment by CesarArellano** [comment]
@LucJosin I hope you can solve this problem and you keep developing this package (version 3.0.0) because your work is impressive

**Comment by LucJosin** [comment]
> Using flutter 3.7.7, on_audio_query 2.6.2 doesn't work.

Configuration 1:
* Pixel 6 Pro
* Android 12 / API 31
* Emulator
* Flutter 3.7.7
* Dart SDK version: 2.19.4

Configuration 2:
* Redmi Note 8
* Android 11 / API 30
* Real device
* Flutter 3.7.7
* Dart SDK version: 2.19.4

Got the same result. On both internal folder and SDCard folder.

Unfortunately i cannot reproduce the bug. But i'll keep looking for.

**Comment by CesarArellano** [comment]
I have tested with this configuration and the package returns an empty list:

- Pixel 5
- Android 13 / API 33
- Emulator
- Flutter 3.7.7
- Dart SDK version: 2.19.4

My audio file is in Downloads Folder and with another app it recognizes the audio.

**Comment by chaliseminas** [comment]
My issue was permission-related - only READ_MEDIA_AUDIO permission was granted, causing empty items to be returned. After granting READ_MEDIA_AUDIO, READ_MEDIA_IMAGES, and READ_MEDIA_VIDEO permissions, the issue was resolved and the code is now working properly.

**Comment by LucJosin** [comment]
> My issue was permission-related - only READ_MEDIA_AUDIO permission was granted, causing empty items to be returned. After granting READ_MEDIA_AUDIO, READ_MEDIA_IMAGES, and READ_MEDIA_VIDEO permissions, the issue was resolved and the code is now working properly.

I forgot to update the README with the new manifest permissions. README: [request-permission](https://github.com/LucJosin/on_audio_query/tree/feat/permission#request-permission)

Could you try adding the new permissions and test the application using the v2.6.2?

cc: @Alvaro1dev, @CesarArellano

**Comment by Alvaro1dev** [comment]
Adding the extra permission didn't work for me. For now I'm using the previous version that works for me. I'll try later to isolate the problem in a new project so you can replicate it.

**Comment by CesarArellano** [comment]
> > My issue was permission-related - only READ_MEDIA_AUDIO permission was granted, causing empty items to be returned. After granting READ_MEDIA_AUDIO, READ_MEDIA_IMAGES, and READ_MEDIA_VIDEO permissions, the issue was resolved and the code is now working properly.
> 
> I forgot to update the README with the new manifest permissions. README: [request-permission](https://github.com/LucJosin/on_audio_query/tree/feat/permission#request-permission)
> 
> Could you try adding the new permissions and test the application using the v2.6.2?
> 
> cc: @Alvaro1dev, @CesarArellano

It only worked for me for Flutter version 3.7.0 onwards.
In Flutter version 3.3.10 it doesn't work for me.

I leave my project:
[https://github.com/CesarArellano/Music-Player-App](url)

**Comment by LucJosin** [comment]
I did more tests

<details>
<summary>Test 1</summary>

### Steps:
* Create a new flutter project **(Flutter 3.3.10 and Dart 2.18.6)**
* Install on_audio_query **(2.6.1)**
* Run the application (with [on_audio_query/example/main](https://github.com/LucJosin/on_audio_query/tree/main/on_audio_query/example/lib/main.dart))

### Config 1
* Pixel 6 Pro
* Android 12 / API 31
* Emulator

#### Result
> Everything works.

### Config 2
* Pixel 6 Pro
* Android 13 / API 33
* Emulator

#### Result
> Not working.
</details>

<details>
<summary>Test 2</summary>

### Steps:
* Create a new flutter project **(Flutter 3.7.7 and Dart 2.19.4)**
* **Run flutter clean**
* Install on_audio_query **Updated from (2.6.1) to (2.6.2)**
* Run the application (with [on_audio_query/example/main](https://github.com/LucJosin/on_audio_query/tree/main/on_audio_query/example/lib/main.dart))
* Add new permissions to [AndroidManifest](https://github.com/LucJosin/on_audio_query/blob/feat/permission/on_audio_query/example/android/app/src/main/AndroidManifest.xml)

### Config 1
* Pixel 6 Pro
* Android 12 / API 31
* Emulator

#### Result
> Everything works.

### Config 2
* Pixel 6 Pro
* Android 13 / API 33
* Emulator

#### Result
> Everything works.
</details>

> Here is the link to my project:
[https://github.com/CesarArellano/Music-Player-App](https://github.com/LucJosin/on_audio_query/issues/url)

I also tried using your project and got the same result. The v2.6.2 works on both 3.3.10-3.7.7 and android 12-13

But, when updating from v2.6.1 to v2.6.2, **i could reproduce the empty list issue**. Fixed that after running *flutter clean* and *flutter pub get*.
